@include('frontend.head')

<h2>Daftar Surat</h2>
<div class="list-group">
		<a href="{{ route('surat1.index') }}" class="list-group-item list-group-item-action"> Surah Al-fatihah </a>
		<a href="{{ route('surat2.index') }}" class="list-group-item list-group-item-action"> Surah Al-Baqarah </a>
		<a href="{{ route('surat3.index') }}" class="list-group-item list-group-item-action"> Surah Ali `Imran </a>
		<a href="{{ route('surat4.index') }}" class="list-group-item list-group-item-action"> Surah An-Nisa` </a>
		<a href="{{ route('surat5.index') }}" class="list-group-item list-group-item-action"> Surah Al-Ma`idah </a>
		<a href="{{ route('surat6.index') }}" class="list-group-item list-group-item-action"> Surah Al-An`am </a>
		<a href="{{ route('surat7.index') }}" class="list-group-item list-group-item-action"> Surah Al-A’raf </a>
		<a href="{{ route('surat8.index') }}" class="list-group-item list-group-item-action"> Surah Al-Anfal </a>
		<a href="{{ route('surat9.index') }}" class="list-group-item list-group-item-action"> Surah At-Taubah </a>
		<a href="{{ route('surat10.index') }}" class="list-group-item list-group-item-action"> Surah Yunus </a>
		<a href="{{ route('surat11.index') }}" class="list-group-item list-group-item-action"> Surah Hud </a>
		<a href="{{ route('surat12.index') }}" class="list-group-item list-group-item-action"> Surah Yusuf </a>
		<a href="{{ route('surat13.index') }}" class="list-group-item list-group-item-action"> Surah Ar-Ra’d </a>
		<a href="{{ route('surat14.index') }}" class="list-group-item list-group-item-action"> Surah Ibrahim </a>
		<a href="{{ route('surat15.index') }}" class="list-group-item list-group-item-action"> Surah Al-Hijr </a>
		<a href="{{ route('surat16.index') }}" class="list-group-item list-group-item-action"> Surah An-Nahl </a>
		<a href="{{ route('surat17.index') }}" class="list-group-item list-group-item-action"> Surah Al-Isra` </a>
		<a href="{{ route('surat18.index') }}" class="list-group-item list-group-item-action"> Surah Al-Kahf </a>
		<a href="{{ route('surat19.index') }}" class="list-group-item list-group-item-action"> Surah Maryam </a>
		<a href="{{ route('surat20.index') }}" class="list-group-item list-group-item-action"> Surah Ta Ha </a>
		<a href="{{ route('surat21.index') }}" class="list-group-item list-group-item-action"> Surah Al-Anbiya </a>
		<a href="{{ route('surat22.index') }}" class="list-group-item list-group-item-action"> Surah Al-Hajj </a>
		<a href="{{ route('surat23.index') }}" class="list-group-item list-group-item-action"> Surah Al-Mu’minun </a>
		<a href="{{ route('surat24.index') }}" class="list-group-item list-group-item-action"> Surah An-Nur </a>
		<a href="{{ route('surat25.index') }}" class="list-group-item list-group-item-action"> Surah Al-Furqan </a>
		<a href="{{ route('surat26.index') }}" class="list-group-item list-group-item-action"> Surah Asy-Syu`ara` </a>
		<a href="{{ route('surat27.index') }}" class="list-group-item list-group-item-action"> Surah An-Naml </a>
		<a href="{{ route('surat28.index') }}" class="list-group-item list-group-item-action"> Surah Al-Qasas </a>
		<a href="{{ route('surat29.index') }}" class="list-group-item list-group-item-action"> Surah Al-`Ankabut </a>
		<a href="{{ route('surat30.index') }}" class="list-group-item list-group-item-action"> Surah Ar-Rum </a>
		<a href="{{ route('surat31.index') }}" class="list-group-item list-group-item-action"> Surah Luqman </a>
		<a href="{{ route('surat32.index') }}" class="list-group-item list-group-item-action"> Surah As-Sajdah </a>
		<a href="{{ route('surat33.index') }}" class="list-group-item list-group-item-action"> Surah Al-Ahzab </a>
		<a href="{{ route('surat34.index') }}" class="list-group-item list-group-item-action"> Surah Saba’ </a>
		<a href="{{ route('surat35.index') }}" class="list-group-item list-group-item-action"> Surah Fatir	 </a>
		<a href="{{ route('surat36.index') }}" class="list-group-item list-group-item-action"> Surah Ya Sin </a>
		<a href="{{ route('surat37.index') }}" class="list-group-item list-group-item-action"> Surah As-Saffat </a>
		<a href="{{ route('surat38.index') }}" class="list-group-item list-group-item-action"> Surah Sad </a>
		<a href="{{ route('surat39.index') }}" class="list-group-item list-group-item-action"> Surah Az-Zumar </a>
		<a href="{{ route('surat40.index') }}" class="list-group-item list-group-item-action"> Surah Al-Mu’min </a>
		<a href="{{ route('surat41.index') }}" class="list-group-item list-group-item-action"> Surah Fussilat </a>
		<a href="{{ route('surat42.index') }}" class="list-group-item list-group-item-action"> Surah Asy-Syura </a>
		<a href="{{ route('surat43.index') }}" class="list-group-item list-group-item-action"> Surah Az-Zukhruf </a>
		<a href="{{ route('surat44.index') }}" class="list-group-item list-group-item-action"> Surah Ad-Dukhan </a>
		<a href="{{ route('surat45.index') }}" class="list-group-item list-group-item-action"> Surah Al-Jasiyah </a>
		<a href="{{ route('surat46.index') }}" class="list-group-item list-group-item-action"> Surah Al-Ahqaf </a>
		<a href="{{ route('surat47.index') }}" class="list-group-item list-group-item-action"> Surah Muhammad </a>
		<a href="{{ route('surat48.index') }}" class="list-group-item list-group-item-action"> Surah Al-Fath </a>
		<a href="{{ route('surat49.index') }}" class="list-group-item list-group-item-action"> Surah Al-Hujurat </a>
		<a href="{{ route('surat50.index') }}" class="list-group-item list-group-item-action"> Surah Qaf </a>
		<a href="{{ route('surat51.index') }}" class="list-group-item list-group-item-action"> Surah Az-Zariyat </a>
		<a href="{{ route('surat52.index') }}" class="list-group-item list-group-item-action"> Surah At-Tur	 </a>
		<a href="{{ route('surat53.index') }}" class="list-group-item list-group-item-action"> Surah An-Najm </a>
		<a href="{{ route('surat54.index') }}" class="list-group-item list-group-item-action"> Surah Al-Qamar </a>
		<a href="{{ route('surat55.index') }}" class="list-group-item list-group-item-action"> Surah Ar-Rahman </a>
		<a href="{{ route('surat56.index') }}" class="list-group-item list-group-item-action"> Surah Al-Waqi’ah </a>
		<a href="{{ route('surat57.index') }}" class="list-group-item list-group-item-action"> Surah Al-Hadid </a>
		<a href="{{ route('surat58.index') }}" class="list-group-item list-group-item-action"> Surah Al-Mujadilah </a>
		<a href="{{ route('surat59.index') }}" class="list-group-item list-group-item-action"> Surah Al-Hasyr </a>
		<a href="{{ route('surat60.index') }}" class="list-group-item list-group-item-action"> Surah Al-Mumtahanah	 </a>
		<a href="{{ route('surat61.index') }}" class="list-group-item list-group-item-action"> Surah As-Saff </a>
		<a href="{{ route('surat62.index') }}" class="list-group-item list-group-item-action"> Surah Al-Jumu’ah </a>
		<a href="{{ route('surat63.index') }}" class="list-group-item list-group-item-action"> Surah Al-Munafiqun	 </a>
		<a href="{{ route('surat64.index') }}" class="list-group-item list-group-item-action"> Surah At-Tagabun </a>
		<a href="{{ route('surat65.index') }}" class="list-group-item list-group-item-action"> Surah At-Talaq </a>
		<a href="{{ route('surat66.index') }}" class="list-group-item list-group-item-action"> Surah At-Tahrim </a>
		<a href="{{ route('surat67.index') }}" class="list-group-item list-group-item-action"> Surah Al-Mulk </a>
		<a href="{{ route('surat68.index') }}" class="list-group-item list-group-item-action"> Surah Al-Qalam </a>
		<a href="{{ route('surat69.index') }}" class="list-group-item list-group-item-action"> Surah Al-Haqqah </a>
		<a href="{{ route('surat70.index') }}" class="list-group-item list-group-item-action"> Surah Al-Ma’arij </a>
		<a href="{{ route('surat71.index') }}" class="list-group-item list-group-item-action"> Surah Nuh </a>
		<a href="{{ route('surat72.index') }}" class="list-group-item list-group-item-action"> Surah Al-Jinn </a>
		<a href="{{ route('surat73.index') }}" class="list-group-item list-group-item-action"> Surah Al-Muzzammil	 </a>
		<a href="{{ route('surat74.index') }}" class="list-group-item list-group-item-action"> Surah Al-Muddassir </a>
		<a href="{{ route('surat75.index') }}" class="list-group-item list-group-item-action"> Surah Al-Qiyamah </a>
		<a href="{{ route('surat76.index') }}" class="list-group-item list-group-item-action"> Surah Al-Insan </a>
		<a href="{{ route('surat77.index') }}" class="list-group-item list-group-item-action"> Surah Al-Mursalat </a>
		<a href="{{ route('surat78.index') }}" class="list-group-item list-group-item-action"> Surah An-Naba’ </a>
		<a href="{{ route('surat79.index') }}" class="list-group-item list-group-item-action"> Surah An-Nazi’at </a>
		<a href="{{ route('surat80.index') }}" class="list-group-item list-group-item-action"> Surah `Abasa </a>
		<a href="{{ route('surat81.index') }}" class="list-group-item list-group-item-action"> Surah At-Takwir </a>
		<a href="{{ route('surat82.index') }}" class="list-group-item list-group-item-action"> Surah Al-Infitar </a>
		<a href="{{ route('surat83.index') }}" class="list-group-item list-group-item-action"> Surah Al-Tatfif </a>
		<a href="{{ route('surat84.index') }}" class="list-group-item list-group-item-action"> Surah Al-Insyiqaq </a>
		<a href="{{ route('surat85.index') }}" class="list-group-item list-group-item-action"> Surah Al-Buruj </a>
		<a href="{{ route('surat86.index') }}" class="list-group-item list-group-item-action"> Surah At-Tariq </a>
		<a href="{{ route('surat87.index') }}" class="list-group-item list-group-item-action"> Surah Al-A’la </a>
		<a href="{{ route('surat88.index') }}" class="list-group-item list-group-item-action"> Surah Al-Gasyiyah </a>
		<a href="{{ route('surat89.index') }}" class="list-group-item list-group-item-action"> Surah Al-Fajr </a>
		<a href="{{ route('surat90.index') }}" class="list-group-item list-group-item-action"> Surah Al-Balad </a>
		<a href="{{ route('surat91.index') }}" class="list-group-item list-group-item-action"> Surah Asy-Syams </a>
		<a href="{{ route('surat92.index') }}" class="list-group-item list-group-item-action"> Surah Al-Lail </a>
		<a href="{{ route('surat93.index') }}" class="list-group-item list-group-item-action"> Surah Ad-Duha </a>
		<a href="{{ route('surat94.index') }}" class="list-group-item list-group-item-action"> Surah Al-Insyirah </a>
		<a href="{{ route('surat95.index') }}" class="list-group-item list-group-item-action"> Surah At-Tin </a>
		<a href="{{ route('surat96.index') }}" class="list-group-item list-group-item-action"> Surah Al-`Alaq </a>
		<a href="{{ route('surat97.index') }}" class="list-group-item list-group-item-action"> Surah Al-Qadr </a>
		<a href="{{ route('surat98.index') }}" class="list-group-item list-group-item-action"> Surah Al-Bayyinah </a>
		<a href="{{ route('surat99.index') }}" class="list-group-item list-group-item-action"> Surah Az-Zalzalah </a>
		<a href="{{ route('surat100.index') }}" class="list-group-item list-group-item-action"> Surah Al-`Adiyat </a>
		<a href="{{ route('surat101.index') }}" class="list-group-item list-group-item-action"> Surah Al-Qari`ah </a>
		<a href="{{ route('surat102.index') }}" class="list-group-item list-group-item-action"> Surah At-Takasur </a>
		<a href="{{ route('surat103.index') }}" class="list-group-item list-group-item-action"> Surah Al-`Asr </a>
		<a href="{{ route('surat104.index') }}" class="list-group-item list-group-item-action"> Surah Al-Humazah </a>
		<a href="{{ route('surat105.index') }}" class="list-group-item list-group-item-action"> Surah Al-Fil </a>
		<a href="{{ route('surat106.index') }}" class="list-group-item list-group-item-action"> Surah Quraisy </a>
		<a href="{{ route('surat107.index') }}" class="list-group-item list-group-item-action"> Surah Al-Ma’un </a>
		<a href="{{ route('surat108.index') }}" class="list-group-item list-group-item-action"> Surah Al-Kausar </a>
		<a href="{{ route('surat109.index') }}" class="list-group-item list-group-item-action"> Surah Al-Kafirun </a>
		<a href="{{ route('surat110.index') }}" class="list-group-item list-group-item-action"> Surah An-Nasr </a>
		<a href="{{ route('surat111.index') }}" class="list-group-item list-group-item-action"> Surah Al-Lahab </a>
		<a href="{{ route('surat112.index') }}" class="list-group-item list-group-item-action"> Surah Al-Ikhlas </a>
		<a href="{{ route('surat113.index') }}" class="list-group-item list-group-item-action"> Surah Al-Falaq </a>
		<a href="{{ route('surat114.index') }}" class="list-group-item list-group-item-action"> Surah An-Nas</a>
	</div>